import {
    DashboardOutlined,
    UnorderedListOutlined,
    UserAddOutlined,
    SettingOutlined,
    ProfileOutlined,
    ToolOutlined,
    LaptopOutlined,
    InsertRowLeftOutlined,
    BankOutlined,
    TruckOutlined,
    DollarOutlined ,
    FileTextOutlined,
    FrownOutlined,
    TransactionOutlined,
    FundProjectionScreenOutlined,
    FundViewOutlined,
    ReadOutlined,
    CommentOutlined,
    ThunderboltOutlined,
    TeamOutlined,
    MessageOutlined,
    AppstoreOutlined,
    ContainerOutlined,
    DesktopOutlined,
    MailOutlined,
    MenuFoldOutlined,
    MenuUnfoldOutlined,
    PieChartOutlined,
    UserOutlined,
    IdcardOutlined,
  } from '@ant-design/icons';
const icons:any = {
    MessageOutlined: <MessageOutlined/>,
    AppstoreOutlined: <AppstoreOutlined/>,
    ContainerOutlined: <ContainerOutlined/>,
    DesktopOutlined: <DesktopOutlined/>,
    MailOutlined: <MailOutlined/>,
    MenuFoldOutlined: <MenuFoldOutlined/>,
    MenuUnfoldOutlined: <MenuUnfoldOutlined/>,
    PieChartOutlined: <PieChartOutlined/>,
    UserOutlined: <UserOutlined/>,
    DashboardOutlined: <DashboardOutlined />,
    UnorderedListOutlined: <UnorderedListOutlined />,
    UserAddOutlined: <UserAddOutlined />,
    SettingOutlined: <SettingOutlined />,
    LaptopOutlined:<LaptopOutlined/>,
    ProfileOutlined: <ProfileOutlined />,
    InsertRowLeftOutlined:<InsertRowLeftOutlined/>,
    BankOutlined:<BankOutlined/>,
    ToolOutlined: <ToolOutlined />,
    TruckOutlined:<TruckOutlined/>,
    DollarOutlined:<DollarOutlined/>,
    FileTextOutlined:<FileTextOutlined/>,
    FrownOutlined:<FrownOutlined/>,
    TransactionOutlined:<TransactionOutlined/>,
    FundProjectionScreenOutlined:<FundProjectionScreenOutlined/>,
    FundViewOutlined:<FundViewOutlined/>,
    ReadOutlined:<ReadOutlined/>,
    CommentOutlined:<CommentOutlined/>,
    ThunderboltOutlined:<ThunderboltOutlined/>,
    TeamOutlined:<TeamOutlined/>,
    IdcardOutlined:<IdcardOutlined/>
  };

  export default icons