"""update_task_tables_to_use_chats

Revision ID: 067888c7e799
Revises: 37f234d11269
Create Date: 2025-07-21 13:31:08.316695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '067888c7e799'
down_revision: Union[str, None] = '37f234d11269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_chats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('annotation_status', sa.String(length=20), nullable=False, comment='标注状态: pending/completed/skipped'),
    sa.Column('annotation_result', sa.String(length=20), nullable=True, comment='标注结果: approved/rejected/flagged'),
    sa.Column('annotation_comment', sa.Text(), nullable=True, comment='标注备注'),
    sa.Column('annotated_by_id', sa.String(length=36), nullable=True),
    sa.Column('annotated_at', sa.DateTime(), nullable=True, comment='标注时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annotated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['annotation_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('task_messages')
    op.add_column('annotation_tasks', sa.Column('total_chats', sa.Integer(), nullable=False, comment='总对话数'))
    op.add_column('annotation_tasks', sa.Column('completed_chats', sa.Integer(), nullable=False, comment='已完成对话数'))
    op.add_column('annotation_tasks', sa.Column('max_annotations_per_chat', sa.Integer(), nullable=False, comment='每个对话最大标注次数'))
    op.drop_column('annotation_tasks', 'completed_messages')
    op.drop_column('annotation_tasks', 'max_annotations_per_message')
    op.drop_column('annotation_tasks', 'total_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_tasks', sa.Column('total_messages', mysql.INTEGER(), autoincrement=False, nullable=False, comment='总消息数'))
    op.add_column('annotation_tasks', sa.Column('max_annotations_per_message', mysql.INTEGER(), autoincrement=False, nullable=False, comment='每条消息最大标注次数'))
    op.add_column('annotation_tasks', sa.Column('completed_messages', mysql.INTEGER(), autoincrement=False, nullable=False, comment='已完成消息数'))
    op.drop_column('annotation_tasks', 'max_annotations_per_chat')
    op.drop_column('annotation_tasks', 'completed_chats')
    op.drop_column('annotation_tasks', 'total_chats')
    op.create_table('task_messages',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('task_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('message_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('annotation_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False, comment='标注状态: pending/completed/skipped'),
    sa.Column('annotation_result', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='标注结果: approved/rejected/flagged'),
    sa.Column('annotation_comment', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='标注备注'),
    sa.Column('annotated_by_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=True),
    sa.Column('annotated_at', mysql.DATETIME(), nullable=True, comment='标注时间'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['annotated_by_id'], ['users.id'], name=op.f('task_messages_ibfk_1')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('task_messages_ibfk_2')),
    sa.ForeignKeyConstraint(['task_id'], ['annotation_tasks.id'], name=op.f('task_messages_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('task_chats')
    # ### end Alembic commands ###
