"""add indexes for task tables

Revision ID: 0b5c022e87f7
Revises: 067888c7e799
Create Date: 2025-08-16 15:16:13.323332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b5c022e87f7'
down_revision: Union[str, None] = '067888c7e799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_annotation_tasks_assigned_to_id', 'annotation_tasks', ['assigned_to_id'], unique=False)
    op.create_index('ix_annotation_tasks_created_by_id', 'annotation_tasks', ['created_by_id'], unique=False)
    op.create_index('ix_annotation_tasks_deadline', 'annotation_tasks', ['deadline'], unique=False)
    op.create_index('ix_annotation_tasks_status', 'annotation_tasks', ['status'], unique=False)
    op.create_index('ix_task_chats_annotation_status', 'task_chats', ['annotation_status'], unique=False)
    op.create_index('ix_task_chats_chat_id', 'task_chats', ['chat_id'], unique=False)
    op.create_index('ix_task_chats_task_id', 'task_chats', ['task_id'], unique=False)
    op.create_index('ix_task_logs_task_id', 'task_logs', ['task_id'], unique=False)
    op.create_index('ix_task_logs_user_id', 'task_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_logs_user_id', table_name='task_logs')
    op.drop_index('ix_task_logs_task_id', table_name='task_logs')
    op.drop_index('ix_task_chats_task_id', table_name='task_chats')
    op.drop_index('ix_task_chats_chat_id', table_name='task_chats')
    op.drop_index('ix_task_chats_annotation_status', table_name='task_chats')
    op.drop_index('ix_annotation_tasks_status', table_name='annotation_tasks')
    op.drop_index('ix_annotation_tasks_deadline', table_name='annotation_tasks')
    op.drop_index('ix_annotation_tasks_created_by_id', table_name='annotation_tasks')
    op.drop_index('ix_annotation_tasks_assigned_to_id', table_name='annotation_tasks')
    # ### end Alembic commands ###
