"""add test1

Revision ID: 151c26c4f213
Revises: c1f5213960dd
Create Date: 2025-07-10 14:41:42.345525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151c26c4f213'
down_revision: Union[str, None] = 'c1f5213960dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_audits', sa.Column('test_field', sa.String(length=20), nullable=True, comment='测试字段'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_audits', 'test_field')
    # ### end Alembic commands ###
