"""add_task_tables

Revision ID: 37f234d11269
Revises: 151c26c4f213
Create Date: 2025-07-21 13:17:06.429154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '37f234d11269'
down_revision: Union[str, None] = '151c26c4f213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='任务标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='任务描述'),
    sa.Column('status', sa.Enum('CREATED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False, comment='任务状态'),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='taskpriority'), nullable=False, comment='任务优先级'),
    sa.Column('total_messages', sa.Integer(), nullable=False, comment='总消息数'),
    sa.Column('completed_messages', sa.Integer(), nullable=False, comment='已完成消息数'),
    sa.Column('deadline', sa.DateTime(), nullable=True, comment='截止时间'),
    sa.Column('created_by_id', sa.String(length=36), nullable=False, comment='创建者ID'),
    sa.Column('assigned_to_id', sa.String(length=36), nullable=True, comment='分配给标注员ID'),
    sa.Column('auto_assign', sa.Boolean(), nullable=False, comment='是否自动分配'),
    sa.Column('max_annotations_per_message', sa.Integer(), nullable=False, comment='每条消息最大标注次数'),
    sa.Column('task_metadata', mysql.JSON(), nullable=True, comment='任务元数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型'),
    sa.Column('description', sa.Text(), nullable=True, comment='操作描述'),
    sa.Column('old_value', mysql.JSON(), nullable=True, comment='操作前的值'),
    sa.Column('new_value', mysql.JSON(), nullable=True, comment='操作后的值'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['annotation_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('annotation_status', sa.String(length=20), nullable=False, comment='标注状态: pending/completed/skipped'),
    sa.Column('annotation_result', sa.String(length=20), nullable=True, comment='标注结果: approved/rejected/flagged'),
    sa.Column('annotation_comment', sa.Text(), nullable=True, comment='标注备注'),
    sa.Column('annotated_by_id', sa.String(length=36), nullable=True),
    sa.Column('annotated_at', sa.DateTime(), nullable=True, comment='标注时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annotated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['annotation_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_messages')
    op.drop_table('task_logs')
    op.drop_table('annotation_tasks')
    # ### end Alembic commands ###
